common/usbc: Fix constness
When building with clang, it reports:

common/usbc/usb_prl_sm.c:2304:44: error: 'prl_tx_states' causes a
section type conflict with 'flag_bit_names'
static __const_data const struct usb_state prl_tx_states[] = {
                                           ^
common/usbc/usb_prl_sm.c:131:37: note: declared here
static __const_data struct bit_name flag_bit_names[] = {
                                    ^
common/usbc/usb_prl_sm.c:2346:44: error: 'prl_hr_states' causes a
section type conflict with 'flag_bit_names'
static __const_data const struct usb_state prl_hr_states[] = {
                                           ^
common/usbc/usb_prl_sm.c:131:37: note: declared here
static __const_data struct bit_name flag_bit_names[] = {
                                    ^

The issue is that flag_bit_names is not const. When making
flag_bit_names const, we must also make the argument to print_bits const
to fix the additional warning:

common/usbc/usb_prl_sm.c:169:56: error: passing 'const struct bit_name
[11]' to parameter of type 'struct bit_name *' discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        print_bits(group, set_or_clear ? "Set" : "Clr", flag, flag_bit_names,
                                                              ^~~~~~~~~~~~~~
common/usbc/usb_prl_sm.c:149:28: note: passing argument to parameter 'names' here
                                      struct bit_name *names,

BRANCH=none
BUG=b:172020503
TEST=make CC=arm-none-eabi-clang BOARD=cret

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I95d28f53755dd23fe288ae70055e09fcf44511ad
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3205487
Reviewed-by: Edward Hill <ecgh@chromium.org>