common/motion_sense: Avoid comparison between negative value and unsigned char
clang fails to compile due to the following:

common/motion_sense.c:1123:34: error: result of comparison of constant -1
with expression of type 'const uint8_t' (aka 'const unsigned char') is
always false [-Werror,-Wtautological-constant-out-of-range-compare]

(in->sensor_odr.sensor_num ==
~~~~~~~~~~~~~~~~~~~~~~~~~ ^

common/motion_sense.c:1454:27: error: result of comparison of constant -1
with expression of type 'const uint8_t' (aka 'const unsigned char') is
always false [-Werror,-Wtautological-constant-out-of-range-compare]

in->spoof.sensor_id == MOTION_SENSE_ACTIVITY_SENSOR_ID) {
~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

As indicated by the TEST line, the output is identical before and after
this change.

BRANCH=none
BUG=b:172020503
TEST=./util/compare_build.sh -b all -j 90
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: Ieb55b385dfe9e07a8a7098ac3b456a0504215d94
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3197753
Reviewed-by: Paul Fagerburg <pfagerburg@chromium.org>