util: Increase buffer size to account for terminating NUL
When building with clang it warns:

util/ecst.c:464:7: error: 'sscanf' may overflow; destination buffer in
argument 3 has size 20, but the corresponding specifier may require size
21 [-Werror,-Wfortify-source]
	main_str_temp) != 1)) {
	^

BRANCH=none
BUG=b:172020503
TEST=./util/compare_build.sh -b all -j 120
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I0556973263ce2b220e64640e585997c44324db55
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3551680
Reviewed-by: Edward Hill <ecgh@chromium.org>