tree: Fix -Wstrict-prototypes warning
The latest clang complains about missing 'void' in function
definition if it's specified in the declaration:

core/cortex-m/vecttable.c:23:21: error: a function declaration without a
prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
void default_handler()
                    ^
                     void

BRANCH=none
BUG=b:230345382, b:172020503
TEST=./util/compare_build.sh -b all -j 120
     => MATCH

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I5a3d95203cc6cbb59676f4a66876a4a6f2946e31
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3750108
Reviewed-by: Ting Shen <phoenixshen@chromium.org>