gsctool: add ability to get/set flash log timestamp base
The recently introduced vendor command is used to get or set flash log
timestamp.

BRANCH=none
BUG=b:132287488
TEST=on the device ran various incarnations of the command (> prompt
     on the Cr50 console, # is the DUT bash):

  > flo 10 10
  > flo
           1:00
          13:0a 0a 0b 0c 0d 0e 0f 10 11 12 13
   ==== afger a few seconds =====
  # /var/tmp/gsctool -a -T
  Current H1 time is 68
   ==== afger some more time =====
   > flo 5 5
   > flo
            1:00
           13:0a 0a 0b 0c 0d 0e 0f 10 11 12 13
          398:05 05 06 07 08 09
   # /var/tmp/gsctool -a -T 300
   error: return value 1
   # /var/tmp/gsctool -a -T 1000000
   > flo 6 6
   > flo
            1:00
           13:0a 0a 0b 0c 0d 0e 0f 10 11 12 13
          398:05 05 06 07 08 09
      1000022:06 06 07 08 09 0a 0b
   # /var/tmp/gsctool -a -T
   Current H1 time is 1000052

Change-Id: I16ceb97a32b4d452705f9df3826151f3e4e45832
Signed-off-by: Vadim Bendebury <vbendeb@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1610721
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Andrey Pronin <apronin@chromium.org>