chip/host: Fix -Wstrict-prototypes warning
ToT clang is complaining about missing 'void' in
function prototype.
chip/host/system.c:136:45:
error: function declaration without a prototype is deprecated
in all versions of C [-Werror,-Wstrict-prototypes]
 test_mockable uintptr_t get_panic_data_start()
                                            ^
                                             void

BUG=b:230345382
TEST=CQ, llvm tot test
BRANCH=none

Signed-off-by: Manoj Gupta <manojgupta@google.com>
Change-Id: I5c9faab7c0d5ca743d001afb6fe359378974bf8e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3615029
Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Daisuke Nojiri <dnojiri@chromium.org>
Commit-Queue: Daisuke Nojiri <dnojiri@chromium.org>
Auto-Submit: Manoj Gupta <manojgupta@chromium.org>