Revert "usb_update: add more test code"
This reverts commit 3a22b8e964571456ba9c348490e0d4c4c46cc648.

Reason for revert: Fails to build on gitlab with Zephyr SDK
```
/builds/zephyr-ec/ec/ec_dir/zephyr/test/usb_updater/src/main.c: In function ‘test_main’:
/builds/zephyr-ec/ec/ec_dir/zephyr/test/usb_updater/src/main.c:34:18: error: ‘MAP_FIXED_NOREPLACE’ undeclared (first use in this function)
   34 |     MAP_SHARED | MAP_FIXED_NOREPLACE, fd, 0);
      |                  ^~~~~~~~~~~~~~~~~~~
```

Original change's description:
> usb_update: add more test code
>
> - Enable RWSIG and test RWSIG related features
> - Test more error cases
>
> BUG=b:287012522
> TEST=./twister -T zephyr/test/usb_updater/ --coverage --jobs=8
>
> Change-Id: I1452f6910df12e833a8792e6d25cb0b59c3ea10f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5574192
> Reviewed-by: Eric Yilun Lin <yllin@google.com>
> Commit-Queue: Ting Shen <phoenixshen@chromium.org>
> Tested-by: Ting Shen <phoenixshen@chromium.org>
> Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>

BUG=b:287012522

Change-Id: I44a98cc9cd8084a0e8e0254d036f2a1d7e2e72f0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5597933
Tested-by: Jeremy Bettis <jbettis@chromium.org>
Auto-Submit: Jeremy Bettis <jbettis@chromium.org>
Reviewed-by: Tristan Honscheid <honscheid@google.com>
Commit-Queue: Tristan Honscheid <honscheid@google.com>