fingerprint: Stopgap to repair public builds
This repairs building bloonchipper and dartmonkey builds
when private lib is unavailable.

There are two issues this remedies:
1) Redefinition of sensor info macros, like FP_SENSOR_RES_X
2) Undefined reference to fp_sensor_maintenance when building
   bloonchipper/dartmonkey non-private image.

All of these issues stem from the way we handle code
when HAVE_FP_PRIVATE_DRIVER is set or faked by a test.
This is a fundamental issues that needs some thought and refactoring.

BRANCH=none
BUG=b:164174822,b:163109916, b:163411883
TEST=# With private
     time make buildall -j
TEST=# Without private
     time make buildall -j
TEST=# With private libs
     # Cherry-pick https://crrev.com/c/2357870 first, then
     # this patch.
     ./util/compare_build.sh -b all -o
     # This confirms that the all output binaries with private-lib
     # did not change at all

Signed-off-by: Craig Hesling <hesling@chromium.org>
Change-Id: If71e3376fb7a904b77f2fc9fc56c8e0daf54db3b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2357430
Reviewed-by: Andrew de los Reyes <adlr@chromium.org>
Reviewed-by: YH Lin <yueherngl@chromium.org>