chip/mt_scp: Fix return type
When building with clang, it warns:

chip/mt_scp/rv32i_common/hostcmd.c:112:9: error: implicit conversion
from enumeration type 'enum ec_error_list' to different enumeration type
'enum ec_status' [-Werror,-Wenum-conversion]
  112 |         return EC_SUCCESS;
      |         ~~~~~~ ^~~~~~~~~~

BUG=b:172020503
TEST=make V=1 CROSS_COMPILE_CC_NAME=clang BOARD=geralt_scp_core1

Change-Id: I55220ffe4b0a8d4e3589d3a322aadbc6bcaa9d34
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/6317340
Commit-Queue: Tom Hughes <tomhughes@chromium.org>
Tested-by: Tom Hughes <tomhughes@chromium.org>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Reviewed-by: Yuval Peress <peress@google.com>
(cherry picked from commit a13da0801df2ce13ff9d6d1b9f350eb4744982d8)