zephyr: Fix broken volteer build
On github, the volteer build was failing with error: 
undefined reference to `ppc_is_vbus_present'
but it was building in the chroot. It seems the chroot linker can
determine that the pd_snk_is_vbus_provided function is never called,
but the zephyr toolchain linker cannot, or perhaps it does missing
function detection before removing unused functions.

Remove pd_snk_is_vbus_provided if CONFIG_USB_PD_VBUS_DETECT_PPC is not
set.

BRANCH=None
BUG=b:194375840
TEST=In docker container:
PROJECT=volteer; PROJECT_SUBDIR=volteer/; VERSION=26; unset TOOLCHAIN
zmake -j1 --zephyr-base "${ZEPHYR_BASE}${VERSION}" \
--modules-dir "${MODULES_DIR}" -l DEBUG configure -b \
-B "${BUILD_DIR}/${PROJECT}" -t ${TOOLCHAIN:-zephyr} \
zephyr/projects/${PROJECT_SUBDIR}${PROJECT}
In chroot: zmake configure -b zephyr/projects/volteer/volteer

Change-Id: I59679a12e89e8b2e5fa2f62dc5fa60d108234d23
Signed-off-by: Jeremy Bettis <jbettis@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3188214
Reviewed-by: Yuval Peress <peress@google.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Reviewed-by: Aaron Massey <aaronmassey@google.com>
Reviewed-by: Parth Malkan <parthmalkan@google.com>
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Commit-Queue: Yuval Peress <peress@google.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: Jeremy Bettis <jbettis@chromium.org>
Auto-Submit: Jeremy Bettis <jbettis@chromium.org>