Revert "Servo v4: reduce RO flash size"
This reverts commit 590a45db85507787af77cf6bfc8ae63499cbf1cc.

BRANCH=none
BUG=b:124465253
TEST=manual,
Running
  sudo servo_updater -b servo_v4 --force -f build/servo_v4/ec.bin
  sudo servo_updater -b servo_v4 --force -f build/servo_v4/ec.bin

passes without failure,
  servo_updater.ServoUpdaterException: usb_updater2 exit with res = 3

Change-Id: Ied9939192c30342bb6314e6dccfcd56d950659ab
Signed-off-by: Todd Broch <tbroch@google.com>
Reviewed-on: https://chromium-review.googlesource.com/1497438
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Todd Broch <tbroch@chromium.org>
Reviewed-by: Diana Z <dzigterman@chromium.org>