Revert "fwk: Fix ignoring powerbutton if lid closed from G3"
It's buggy:

```
/mnt/host/source/src/platform/ec/zephyr/program/framework/src/power_button_x86.c: In function 'set_initial_pwrbtn_state':
/mnt/host/source/src/platform/ec/zephyr/program/framework/src/power_button_x86.c:257:17: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
  257 |                 if (!lid_is_open())
      |                 ^~
/mnt/host/source/src/platform/ec/zephyr/program/framework/src/power_button_x86.c:259:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  259 |                         return;
      |                         ^~~~~~
```

This reverts commit 637d4d5bc00756eb02c206dd529168d3758e5648.

Signed-off-by: Daniel Schaefer <dhs@frame.work>
(cherry picked from commit 7853b66ec92817d74a3c83cb28b732a7832805ad)