Revert "iteflash: speed up data write"
This reverts commit 3430629ed4e993594d83e9ea22f984f2cf5fce76.

Reason for revert: Broke EC build

util/iteflash.c: In function ‘is_empty_page’:
util/iteflash.c:1216:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode

  for (int i = 0; i < size; i++) {
  ^

Original change's description:
> iteflash: speed up data write
>
> In Cherry/Asurada, around 60% of the flash is not used. Skip writing
> empty contents makes flash_ec runs 2x faster.
>
> BUG=none
> TEST=Run `time util/flash_ec --board=cherry --image build/cherry/ec.bin`
>        Before this patch: 5min 54s
>        After:             2min 33s
>      And make sure the content is good.
> BRANCH=none
>
> Signed-off-by: Ting Shen <phoenixshen@google.com>
> Change-Id: I6aa5c3c00e2494b87a139f7a09aad9734e68c98d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2785510
> Reviewed-by: Dino Li <dino.li@ite.corp-partner.google.com>
> Reviewed-by: Eric Yilun Lin <yllin@chromium.org>
> Commit-Queue: Ting Shen <phoenixshen@chromium.org>
> Tested-by: Ting Shen <phoenixshen@chromium.org>

Bug: none
Change-Id: I5efd9197b934ad8014739b81625475706ad3b39a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2796375
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Aseda Aboagye <aaboagye@chromium.org>
Commit-Queue: Aseda Aboagye <aaboagye@chromium.org>
Tested-by: Aseda Aboagye <aaboagye@chromium.org>