UCSI/PPM: fix remote_tests compilation error in cros_sdk
This patch fixes compilation error of remote_tests when
compilation is being done in cros_sdk:

../ppm_common.c: In function ‘ppm_common_execute_pending_cmd’:
../ppm_common.c:273:3: error: a label can only be part of
a statement and a declaration is not a statement
  273 |   struct ucsiv3_ack_cc_ci_cmd *ack_cmd =
      |   ^~~~~~

The failure happenss on clang++ version:

Chromium OS 18.0_pre510928-r60 clang version 18.0.0
(/mnt/host/source/src/third_party/llvm-project
82e851a407c52d65ce65e7aa58453127e67d42a0)

The compilation in the cros_sdk is require to avoid
mismatch of libstdc++.

BUG=b:319166426
TEST=./um_ppm -v -b 20 -g 1 -l 2 -k /dev/ucsi_um_test-0

Change-Id: I749896b6433ef72fa7ad6d1f76c9c28bd4e0058c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/5361558
Reviewed-by: Daisuke Nojiri <dnojiri@chromium.org>
Tested-by: Łukasz Bartosik <ukaszb@google.com>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Commit-Queue: Łukasz Bartosik <ukaszb@google.com>