driver/led: Remove unused function
Building with clang:

driver/led/lm3630a.c:23:19: error: unused function 'lm3630a_read'
[-Werror,-Wunused-function]
static inline int lm3630a_read(uint8_t reg, int *val)

BRANCH=none
BUG=b:172020503
TEST=make CC=arm-none-eabi-clang BOARD=aleena

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: If4a26261d41f470c2cb86208e3c1eaada0b2ff3e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3202999
Reviewed-by: Daisuke Nojiri <dnojiri@chromium.org>