core/cortex-m: get_interrupt_context is only used inside CONFIG_TASK_PROFILING
get_interrupt_context is only called from code inside #ifdef
CONFIG_TASK_PROFILING.

clang emits an unused function warning for this:

core/cortex-m/task.c:238:19: error: unused function
'get_interrupt_context' [-Werror,-Wunused-function]
static inline int get_interrupt_context(void)

BRANCH=none
BUG=chromium:931797
TEST=make buildall -j

Change-Id: I5ba68d1a58a966eeecb5abdb3cb87fa2684f359b
Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/1660017
Reviewed-by: Daisuke Nojiri <dnojiri@chromium.org>
Reviewed-by: Vadim Bendebury <vbendeb@chromium.org>