util/ectool: Use UINT32_MAX instead of -1
When compiling with C++, the conversion from "int" to "unsigned int"
generates a compiler error:

util/ectool.cc:5545:19: error: constant expression evaluates to -1 which
cannot be narrowed to type 'uint32_t' (aka 'unsigned int')
[-Wc++11-narrowing]
                        .number_data = -1,
			               ^~

BRANCH=none
BUG=b:144959033
TEST=make buildall

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: If810a0f68cfdf09c3ca44a7e9233006cad188e39
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2870385
Reviewed-by: Diana Z <dzigterman@chromium.org>