PRESUBMIT: add a presubmit to check for unnecessary Kconfig options
Add a presubmit to read the current Kconfig options and check any
project config file for options that are set automatically from
devicetree nodes and can be removed.

Example error:

ERROR: zephyr/program/nissa/xivur/project.conf:7: unnecessary config
option CONFIG_PLATFORM_EC_FAN=y (depends on DT_HAS_CROS_EC_FANS_ENABLED
&& PLATFORM_EC)

BRANCH=none
BUG=none
TEST=manually, creating test CLs
TEST=./util/check_zephyr_project_config.py -d $( find -name '*.conf' )
TEST=./util/check_zephyr_project_config.py -d $( find -name '*.overlay' )
TEST=./util/check_zephyr_project_config.py -d $( find -name '*_defconfig' )
TEST=./util/check_zephyr_project_config_unittest.py

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Change-Id: I55c224b9bf96d6768460c182d2f11b6d33dcbab0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/4126617
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Reviewed-by: Jack Rosenthal <jrosenth@chromium.org>