tree: Fix LED enum type
"enum ec_led_colors" was used here instead of "enum led_color".

Fixes the following clang warning:

error: implicit conversion from enumeration type
'enum led_color' to different enumeration type 'enum ec_led_colors'
[-Werror,-Wenum-conversion]

This is the same fix as commit 533640b6d2ce1189b8c0559ec69e1d64202d2c8b,
but this should fix all instances. These usages were found with:

git grep --name-only 'enum led_color' | xargs grep ec_led_colors

As indicated by the TEST line, all boards match with this change, except
for bloog since it uses the incorrect enum in two places.

BRANCH=none
BUG=b:172020503
TEST=CC=arm-none-eabi-clang BOARD=<affected board>
TEST=./util/compare_build.sh -b all -j 120
     => All match except bloog

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: I75cff3769d5b3b82b9218bfb8584f449fb6a781f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3203936
Reviewed-by: Aseda Aboagye <aaboagye@chromium.org>