chip/it83xx: Fix return type
When building with clang, it warns:

chip/it83xx/spi.c:396:9: error: implicit conversion from enumeration
type 'enum ec_error_list' to different enumeration type 'enum ec_status'
[-Werror,-Wenum-conversion]
  396 |         return EC_SUCCESS;
      |         ~~~~~~ ^~~~~~~~~~

BUG=b:172020503
TEST=make V=1 CROSS_COMPILE_CC_NAME=clang BOARD=pico

Change-Id: Ic471cb0ff12318171f1b6a5d596f86ba4a1a984f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/6317339
Reviewed-by: Rob Barnes <robbarnes@google.com>
Reviewed-by: Eric Yilun Lin <yllin@google.com>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Tested-by: Tom Hughes <tomhughes@chromium.org>
Commit-Queue: Tom Hughes <tomhughes@chromium.org>
(cherry picked from commit 6cb13d336cb53e979de62345eaf185e3f2fa43f9)