core/cortex-m0: Fix atomic.h compilation with clang
clang warns about the following invalid instructions in the inline
assembly:

core/cortex-m0/atomic.h:44:9: error: invalid instruction, any one of the
following would fix this:

<inline asm>:4:1: note: instantiated into assembly here
orr r3, r3, r2
^
<inline asm>:4:1: note: instantiated into assembly here
bic r2, r2, r1
^

ld.lld: error: <inline asm>:1:5: invalid instruction, any one of the
following would fix this:
           mov    r1, #0
	              ^

ld.lld: error: <inline asm>:4:1: invalid instruction, any one of the
following would fix this:
sub r2, r2, r1
^

The Cortex M0 instruction set only has the variant of these instructions
that set the condition codes (e.g., "bics", "orrs"):
https://developer.arm.com/documentation/ddi0432/c/CHDCICDF.

The "s" at the end indicates that the condition flags will be updated,
but we already indicate that we are clobbering condition codes with "cc"
in the inline asm.

We need to add ".syntax unified" to tell gcc's assembler we're using
unified assembler language
(https://developer.arm.com/documentation/dui0473/c/BABJIHGJ):

/tmp/ccnA5Gkb.s:15936: Error: instruction not supported in Thumb16 mode
-- `orrs r1,r1,r3'
/tmp/ccnA5Gkb.s:15996: Error: instruction not supported in Thumb16 mode
-- `bics r1,r1,r3'

BRANCH=none
BUG=b:172020503
TEST=CC=clang make BOARD=burnet
TEST=CC=clang make BOARD=servo_micro
TEST=make buildall

Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Change-Id: Ifafaf67080e25ab2c5d2aad3efc90a9d61978bf9
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3188639
Reviewed-by: Ting Shen <phoenixshen@chromium.org>