zephyr: panic: Fix warning when building with clang
Building with clang warns:

zephyr/shim/src/panic.c:158:17: error: converting the enum constant to
a boolean [-Werror,-Wint-in-bool-context]
  158 |         if (PANIC_ARCH && esf) {
      |                        ^

Avoid mixing integers (#define PANIC_ARCH 0) and enums (enum
panic_arch), by adding a new value to "enum panic_arch" that represents
an unsupported architecture.

BUG=b:407560601, b:172020503
TEST=zmake compare-builds -a

Change-Id: I21f30269c0c5692d7e1c1ab5b89bbfff42692dc6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/6303164
Tested-by: Tom Hughes <tomhughes@chromium.org>
Commit-Queue: Tom Hughes <tomhughes@chromium.org>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
(cherry picked from commit 4a6a24b7be383f8af9043a216cbbc7bbca2f44c2)